title: "The campaign for fair pay on campus"
description: "A simple design in semantic markup"

safe: true

exclude: [config.ru, Gemfile, Gemfile.lock, LICENSE.txt, Procfile, Rakefile, README.md, vendor]
